// Storefront Components
export { FeedCard } from './components/storefront/FeedCard'
export { GridCard } from './components/storefront/GridCard'
export { ProductGallery } from './components/storefront/ProductGallery'
export type { GallerySection } from './components/storefront/ProductGallery'
export { ProductPanel } from './components/storefront/ProductPanel'
export { ProductSwiper } from './components/storefront/ProductSwiper'
export { QuickAddButton } from './components/storefront/QuickAddButton'
export { ColorSquares } from './components/storefront/ColorSquares'
export { ColorStrip } from './components/storefront/ColorStrip'

// Admin Components
export { ProductEditor } from './components/admin/ProductEditor'
export { ProductImageManager } from './components/admin/ProductImageManager'
export { ProductThumb } from './components/admin/ProductThumb'
export { ProductsBulkEdit } from './components/admin/ProductsBulkEdit'
export { ProductsList } from './components/admin/ProductsList'
export { VariantBuilder } from './components/admin/VariantBuilder'
export type { BuilderOption, BuilderGroup } from './components/admin/VariantBuilder'
export { VariantManager } from './components/admin/VariantManager'
export { VariantStager } from './components/admin/VariantStager'
export type { StagedVariantGroup } from './components/admin/VariantStager'

// Actions / Services
export * from './services/products'
export * from './services/product-filters'
export * from './services/variants'
export * from './consts/variant-presets'
export * from './lib/feed-rhythm'
export * from './lib/product-detail'
